/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TemaTest;

public class App {
    
    public App() {}
    public static void main(java.lang.String[] args) {
        if (args == null) {
            System.out.println("Hello world!");
        }
        Command c = new Command(args);
        c.execute();
    }
}